name: ninja_trader
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'
dependencies:
  flutter:
    sdk: flutter

  #UI
  cupertino_icons: ^1.0.2

  #State Management
  flutter_bloc: ^8.1.2

  #utils
  equatable: ^2.0.5
  build_runner: ^2.3.3
  copy_with_extension: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  #utils
  build_runner:
  copy_with_extension:

flutter:
  uses-material-design: true
  assets:
    - assets/